#!/bin/sh

killall sxhkd; sxhkd &
killall picom; picom -b --experimental-backends &
killall polybar; sh ~/.config/polybar/launch.sh --forest &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config focus_follows_pointer true
bspc config border_width 2
bspc config window_gap 15

PADDING=60
bspc config left_padding $PADDING
bspc config right_padding $PADDING
bspc config bottom_padding $((PADDING / 2)) 
bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config swallow_first_click false
bspc config normal_border_color "#282828"
bspc config active_border_color "#ebdbb2"
bspc config focused_border_color "#458588"

