#!/bin/sh

killall sxhkd; sxhkd &
killall picom; picom -b --experimental-backends &
killall polybar; sh ~/.config/polybar/launch.sh --forest
~/.fehbg

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config focus_follows_pointer true
bspc config border_width 2
bspc config window_gap 25
bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config swallow_first_click false
bspc config normal_border_color "#282828"
bspc config active_border_color "#ebdbb2"
bspc config focused_border_color "#fe8019"
